steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/dash-cloudrun:$COMMIT_SHA', './CLOUD/DASH']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/dash-cloudrun:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'dash-cloudrun'
  - '--image'
  - 'gcr.io/$PROJECT_ID/dash-cloudrun:$COMMIT_SHA'
  - '--region'
  - 'europe-central2'
images:
- 'gcr.io/$PROJECT_ID/dash-cloudrun:$COMMIT_SHA'	