name: kyd_update

on:
  schedule:
    - cron: '7 7 * * 1-5' # Every weekday at 10.30 Istanbul
    - cron: '7 10 * * 1-5'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable

      - name: Remove default Chromium
        run: sudo apt purge chromium-browser

      - name: Install a new Chromium
        run: sudo apt install -y chromium-browser

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r CODE/GATHER_DATA/kyd_requirements.txt
      
      - name: execute py script
        run: python CODE/GATHER_DATA/gather_kyd.py

      - name: Commit the changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Results from tefas_update" || echo "No changes to commit"
          git push origin || echo "No changes to commit"-
