on:
  push:
    branches: main

jobs:
  import-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.TOKEN }}
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
	with:
          use-public-rspm: true

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::tidyverse, any::zoo

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("./Code.R")'

      - name: Commit results
        run: |
          git config --local user.email "robobesplus@gmail.com"
          git config --local user.name "robobes"
          git add Output.RData
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"