on:
  push:
    branches: main

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::zoo
	    any::arrow

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("Code.R")'

      - name: Commit results
        run: |
          git config --local user.email "robobesplus@gmail.com"
          git config --local user.name "robobes"
          git add Output.RData
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"